addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-contrib-10
env:
  - PATH=".:/usr/lib/postgresql/10/bin:$PATH"
install: "true"
language: erlang
otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3
  - 18.3
  - 17.5
script:
  - make elvis
  - make test
  - make dialyzer
